<a href="https://colab.research.google.com/github/Funmilayo-Aina/DEEP-LEARNING-PROJECTS/blob/main/Tensorflow2_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

# Lets check the current recommended Version 
tf.__version__

'2.6.0'

Creating a Tensor

In [3]:
# Rank 0 Tensor (Scaler)
a = tf.constant(3)
print(a) # 'a' is a Rank 0 Tensor (0 dimensional array) of Int32

tf.Tensor(3, shape=(), dtype=int32)


In [ ]:
# Rank 1 Tensor 
b = tf.constant([1 , 2 , 3 , 4])
print(b) # 'b' is a Rank 1 Tensor of Int32

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [4]:
# Rank 2 Tensor 
c = tf.constant([[1 , 2] , [3 , 4]])
print(c) # 'c' is a Rank 2 Tensor of Int32

# Similarly we can create Tensor of Any order 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


Converting a Numy array to Tensor

In [5]:
array = np.array([1 , 2 , 3 , 4])
print(" Before " , array)
array = tf.convert_to_tensor(array)
print(" After " , array)

 Before  [1 2 3 4]
 After  tf.Tensor([1 2 3 4], shape=(4,), dtype=int64)


Arthematic operations on Tensor

In [6]:
# Sample 2D tensor
tensor = tf.constant([[1 , 2] , [3 , 4]])

In [7]:
# Add 1 to all positions 
tensor = tf.add(tensor , 1)
print(" Added 1 " , tensor)

 Added 1  tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)


In [8]:
# Sub 1 from all positions 
tensor = tf.subtract(tensor , 1)
print(" Subtracted 1 " , tensor)

 Subtracted 1  tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [9]:
# Div 2 on all positions 
tensor = tf.divide(tensor , 2)
print(" Divide by 2 " , tensor)

 Divide by 2  tf.Tensor(
[[0.5 1. ]
 [1.5 2. ]], shape=(2, 2), dtype=float64)


In [10]:
# Multiply with 2 
tensor = tf.multiply(tensor , 2)
print(" Multiply by 2 " , tensor)

# you can also perform arthematic operations over vectors 

 Multiply by 2  tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float64)


Matrix Multiplication

In [11]:
tensor = tf.constant([[1 , 2] , [3 , 4]])
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [12]:
tf.multiply(tensor , tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

Activations

In [13]:
tensor = tf.constant([[1 , 2] , [5 , 10]] , dtype=tf.float64)
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [ ]:
# Applying softmax 
tf.nn.softmax(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.26894142, 0.73105858],
       [0.00669285, 0.99330715]])>

In [14]:
# Applying sigmoid 
tf.nn.sigmoid(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.73105858, 0.88079708],
       [0.99330715, 0.9999546 ]])>

In [15]:
# Applying relu 
tf.nn.relu(tensor)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

In [16]:
# Applying lrelu 
tf.nn.leaky_relu(tensor)

# Tensorflow has all the Activation functions built it and ready to use 

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 1.,  2.],
       [ 5., 10.]])>

Optimizers

In [17]:
# Tensorflow has all Optimizers that we discussed in the class 

Optimizer = tf.keras.optimizers.Adam()
print(Optimizer) # Refers to Optimizer class created 

Basic Neural Network Structure

In [18]:
# Start your model with Sequential Object  
model = tf.keras.models.Sequential()
# Next add in your Input object and Specify the Dimension you want to pass in 
model.add(tf.keras.Input(shape=(10,)))
# Add in your Neurons of 1st layer
model.add(tf.keras.layers.Dense(32))
# 2nd layer 
model.add(tf.keras.layers.Dense(16))

# print summary to undertstand your neural network flow
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                352       
_________________________________________________________________
dense_1 (Dense)              (None, 16)                528       
Total params: 880
Trainable params: 880
Non-trainable params: 0
_________________________________________________________________
